FROM registry.access.redhat.com/ubi9/nodejs-22:latest AS builder
COPY --chown=default:root package.json ./
RUN npm install --omit=dev
COPY --chown=default:root src/ ./src/

FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:latest
WORKDIR /opt/app-root/src
COPY --from=builder --chown=1001:0 /opt/app-root/src/node_modules ./node_modules
COPY --from=builder --chown=1001:0 /opt/app-root/src/package.json ./package.json
COPY --from=builder --chown=1001:0 /opt/app-root/src/src ./src
USER 1001:0
EXPOSE 8080
CMD ["node", "src/server.js"]
