"""Source for the ``sitecustomize.py`` shipped into job pods.

The RHOAI enterprise MLflow (``--enable-workspaces``) requires every request to
carry a Kubernetes bearer token *and* an ``X-MLFLOW-WORKSPACE`` header (workspace
== namespace). Job pods talk to it with a vanilla ``mlflow`` client (the ``mlflow``
CLI in pre/post commands, plus TRL's ``report_to: mlflow`` auto-logging), which
has no built-in way to send a custom header.

To avoid rebuilding the job images, the worker delivers this text as
``sitecustomize.py`` in the job's config dir and puts that dir on ``PYTHONPATH``.
Python auto-imports ``sitecustomize`` at interpreter startup in every job
subprocess, which registers an MLflow ``RequestHeaderProvider`` that adds the
bearer token (re-read per request so a rotated projected token is picked up) and
the workspace header. Inert unless ``AMORTIZED_MLFLOW_WORKSPACE_AUTH=1``.

TLS trust and the bearer token path are handled by core MLflow env vars
(``MLFLOW_TRACKING_SERVER_CERT_PATH`` / ``MLFLOW_TRACKING_INSECURE_TLS``); this
provider only supplies the two headers.
"""

from __future__ import annotations

SITECUSTOMIZE_SOURCE = '''\
"""Auto-loaded (via PYTHONPATH) in amortized job pods.

Registers an MLflow RequestHeaderProvider that authenticates to the RHOAI
enterprise MLflow: a Kubernetes bearer token (re-read per request so a rotated
projected service-account token is picked up) plus the X-MLFLOW-WORKSPACE header
(workspace == namespace). Inert unless AMORTIZED_MLFLOW_WORKSPACE_AUTH=1, so a
self-hosted MLflow is unaffected. Generated by amortized; do not edit.
"""

import os

_TOKEN_FILE = os.environ.get(
    "AMORTIZED_MLFLOW_TOKEN_FILE",
    "/var/run/secrets/kubernetes.io/serviceaccount/token",
)
_NS_FILE = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
_WORKSPACE_HEADER = "X-MLFLOW-WORKSPACE"


def _read(path):
    try:
        with open(path) as fh:
            return fh.read().strip()
    except OSError:
        return ""


def _install():
    if os.environ.get("AMORTIZED_MLFLOW_WORKSPACE_AUTH") != "1":
        return
    try:
        from mlflow.tracking.request_header.abstract_request_header_provider import (
            RequestHeaderProvider,
        )
        from mlflow.tracking.request_header.registry import (
            _request_header_provider_registry,
        )
    except Exception:
        return

    workspace = os.environ.get("MLFLOW_WORKSPACE") or _read(_NS_FILE)

    class _AmortizedWorkspaceAuth(RequestHeaderProvider):
        def in_context(self):
            return bool(_read(_TOKEN_FILE))

        def request_headers(self):
            headers = {}
            token = _read(_TOKEN_FILE)
            if token:
                headers["Authorization"] = "Bearer " + token
            if workspace:
                headers[_WORKSPACE_HEADER] = workspace
            return headers

    _request_header_provider_registry.register(_AmortizedWorkspaceAuth)


_install()
'''
