apiVersion: v1
kind: Namespace
metadata:
  name: amortized-nmalepat
  labels:
    app: amortized
    environment: dev
    owner: nmalepat
---
apiVersion: v1
kind: Namespace
metadata:
  name: amortized-nmalepat-jobs
  labels:
    app: amortized
    environment: dev
    owner: nmalepat
