apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: amortized
  labels:
    app: amortized
    component: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
