apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../dev/minio.yaml
  - ../dev/mlflow.yaml
  - ../dev/s3-secret.yaml
  - ../dev/minio-init.yaml
  - ../dev/postgres.yaml
  - nodeport-services.yaml

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
