apiVersion: v1
kind: Namespace
metadata:
  name: amortized-dev
  labels:
    app: amortized
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: amortized-dev-jobs
  labels:
    app: amortized
    environment: dev
