apiVersion: v1
kind: Namespace
metadata:
  name: amortized-mathale
  labels:
    app: amortized
    environment: dev
    owner: mathale
---
apiVersion: v1
kind: Namespace
metadata:
  name: amortized-mathale-jobs
  labels:
    app: amortized
    environment: dev
    owner: mathale
