apiVersion: v1
kind: ConfigMap
metadata:
  name: amortized-config
  namespace: amortized-dev
  labels:
    app: amortized
    component: server
data:
  AMORTIZED_COMPUTE_BACKEND: "kubernetes"
  AMORTIZED_COMPUTE_NAMESPACE: "amortized-dev-jobs"
  AMORTIZED_IMAGE_REGISTRY: "ghcr.io/amortized-ai"
  AMORTIZED_IMAGE_PULL_POLICY: "IfNotPresent"
  AMORTIZED_EXTERNAL_URL: "http://amortized-server.amortized-dev.svc.cluster.local:8000"
  AMORTIZED_MLFLOW_TRACKING_URI: "http://mlflow.amortized.svc.cluster.local:5000"
  AMORTIZED_S3_BUCKET: "amortized"
