kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Shared: MLflow
      - containerPort: 31082
        hostPort: 31082
        protocol: TCP
      # meyceoz: studio=31100, server=31101
      - containerPort: 31100
        hostPort: 31100
        protocol: TCP
      - containerPort: 31101
        hostPort: 31101
        protocol: TCP
      # ssudalai: studio=31110, server=31111
      - containerPort: 31110
        hostPort: 31110
        protocol: TCP
      - containerPort: 31111
        hostPort: 31111
        protocol: TCP
      # mathale: studio=31120, server=31121
      - containerPort: 31120
        hostPort: 31120
        protocol: TCP
      - containerPort: 31121
        hostPort: 31121
        protocol: TCP
      # nmalepat: studio=31130, server=31131
      - containerPort: 31130
        hostPort: 31130
        protocol: TCP
      - containerPort: 31131
        hostPort: 31131
        protocol: TCP
      # esivaram: studio=31140, server=31141
      - containerPort: 31140
        hostPort: 31140
        protocol: TCP
      - containerPort: 31141
        hostPort: 31141
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /dev/null
        containerPath: /var/run/nvidia-container-devices/all
