apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amortized-server-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "amortized.labels" . | nindent 4 }}
    component: server
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "amortized.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
