{{- if .Values.studio.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: amortized-studio
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "amortized.labels" . | nindent 4 }}
    component: studio
spec:
  {{- with .Values.studio.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: amortized-studio
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
